### ISSUE TITLE
How to detect "STOP"ed or "CLEAR"ed layers?

### ISSUE THREAD

**Issue by johnsanders** [olzzon/casparcg-state-scanner#27]
Hello!  Trying to figure out how to determine if a layer has been stopped.

Say we send `PLAY 1-1 MY_VIDEO_CLIP`

The graphql api shows the channel 1 / layer 1 foreground name as "MY_VIDEO_CLIP.mp4"
Perfect!

Now we send `STOP 1-1`

The graphql api still shows channel 1 / layer 1 as "MY_VIDEO_CLIP.mp4"

Best I can tell from watching the OSC messages coming from Caspar, there's a good reason for that..
There's no specific message for the STOP event, so this application has no way to know that the media has changed.

Seems the only way to detect that a channel's state changed to stopped is that an OSC message  for layer->foreground->producer changes from "ffmpeg" to "empty."

So a few questions..

1- Am I right?  Or am i totally misunderstanding how this whole thing works?
2- If I'm right, could a solution be to include layer->foreground-> producer in the graphql schema.  Then on the client side, i can check for that being equal to 'empty' and know the layer is stopped.

If that's a solution, I can try to implement that and send a pull request.

Thanks for a great application!

**Comment by olzzon** [comment]
Yes, the data is coming from the CasparCG OSC.

**Comment by olzzon** [comment]
Yes the data is coming from CasparCG´s OSC protocol and from the ACMP protocol (depending on the CCG version.
As there's so many ways a clip can be started or stopped (or stopped by itself) and as the different versions of CCG reports differently. In CasparCG Clip Tool I did subscripe the time from the Statescanner and check if it was stop or was playing by seeing if the timeleft had changed.

**Comment by olzzon** [comment]
But if the way you propose does the job, feel free to implement, it would be great to have a subscription of "playing" state :)

**Comment by phillipseamore** [comment]
On a sidenote - I've implemented these events in OSC for a few years.  However I've always gotten some resistance to adding them to CCG.  Here's a PR from 2018 (for NRK fork): https://github.com/nrkno/tv-automation-casparcg-server/pull/12

**Comment by olzzon** [comment]
John Sanders has made an implementation that is merged now

**Comment by johnsanders** [comment]
Thanks for merging that... it does address my issue, but I'm not sure it's a magic bullet for "playing" state.

I was going to do a second PR adding a layer "playing" attribute, but It seems that if a non-looping clip reaches the end and stops, Caspar continues to send "ffmpeg" as the producer, which makes sense.  But it also continues to send "paused: false" messages, which makes less sense.  To me at least.

I'll have a think about how to watch timeleft, as you said, for that information.  I imagine it would be good to have a simple 'playing' state rather than getting blasted by constant timeleft updates.

**Comment by olzzon** [comment]
Yes, I think it would make sense to have he "playing?" state calculated inside the sate-scanner instead of in the client.
So feel free to give it a shot 👍

**Comment by olzzon** [comment]
@johnsanders be aware that I´ll change the default branch to develop, latest commit was merged into the master, so if you do a pr to develop (including the last pr) then we should be on track again.
